# Generated by Django 3.1.7 on 2021-03-28 17:34

from django.db import migrations
from backend.models import User


class Migration(migrations.Migration):

    def create(apps, schema_editor):
        User.objects.create_superuser(
            first_name="Admin",
            last_name="Istrator",
            email="admin@conffiliate.com",
            password="admin",
        )

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create),
    ]
